### ISSUE TITLE
Translate to Shapefile

### ISSUE THREAD

**Issue by aldunn4** [DOI-USGS/gems-tools-arcmap#90]
At the end of last year, when running the Translate to Shapefile tool in ArcMap, we got an error about the StandardLithology table. I had posted on Gitter in hopes of a quick answer as we were running up against a deadline, but I just now got around to trying the recommended fix.  I did get the tool to work either by removing the StandardLithology table, as it is not required, or by populating it with data. I have noticed the tool still produces a shapefile for other empty feature classes and tables though. I know there are groups meeting about additional as-needed tables that can be added to GeMS for geochemistry, geophysics, engineering, land classification, etc. Can this tool be made so it skips over any empty feature class or table, even if it's optional?

**Comment by ethoms-usgs** [comment]
Ah, I see the problem (hopefully). Try again, I just pushed another version.

**Comment by aldunn4** [comment]
A new error this time! I can provide the whole results if necessary this is just the last thing it said with the errors.

...
Processing feature data set CorrelationOfMapUnits...
7 feature classes in here
CartographicLines
    Dumping COMU_CMUMapUnitPolysLabels.shp...
    Finished dump
    Dumping COMU_CMUMapUnitPolys.shp...
    Finished dump
    Dumping COMU_CMUMapUnitPoints.shp...
    Finished dump
    Dumping COMU_CMUGeochronPoints.shp...
    Finished dump
    Dumping COMU_CMUContactsAndFaults.shp...
    Finished dump
    Dumping COMU_CMUCartographicLines.shp...
    Finished dump
    Dumping COMU_CMUMapUnitLines.shp...
    Finished dump
Failed script TranslateToShape...

Traceback (most recent call last):
  File "D:\gems-tools-arcmap-master\Scripts\GeMS_TranslateToShape_Arc10.py", line 463, in <module>
    main(newgdb, ows, gdb)
  File "D:\gems-tools-arcmap-master\Scripts\GeMS_TranslateToShape_Arc10.py", line 439, in main
    if arcpy.GetCount_management(tb) > 0:
NameError: global name 'tb' is not defined

Failed to execute (TranslateToShape).
Failed at Wed Apr  5 13:11:05 2023 (Elapsed Time: 9 minutes 0 seconds)

**Comment by ethoms-usgs** [comment]
Arg, typo. Fixed it. Try again. Sorry for the back and forth, but ArcMap is still not opening for me.

**Comment by aldunn4** [comment]
It worked, thank you!

**Comment by ethoms-usgs** [comment]
Good to hear! I will close this issue.
